- name: create a user
  hosts: all
  become: true
  vars_files:
    - secret-1.yaml
  tasks:
  - name: creating a user
    user:
      name: "{{ username }}"
      password: "{{ pwhash | password_hash ( 'sha512' ) }}"

  - debug:
      msg: "user name is {{ username | upper }}"    