- name: Remove Apache from Amz Linux 2 servers
  hosts: webservers
  become: yes
  tasks:
  - name: Remove the Apache package
    ansible.builtin.yum:
      name: httpd
      state: absent

- name: Remove Apache from Ubuntu servers
  hosts: ubuntuservers
  become: true
  tasks:
  - name: Remove the Apache package
    ansible.builtin.apt:
      name: apache2
      state: absent
  - name: Remove dependencies that are no longer required
    ansible.builtin.apt:
      autoremove: yes
      purge: yes