---
- name: Create a VPC and Subnets
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vpc_setup
    - bastion_setup

  tasks:
    - name: Create a VPC
      ansible.builtin.ec2_vpc_net:
        cidr_block: "{{ vpcCidr }}"
        name: "{{ vpc_name }}"
        region: "{{ region }}"
        state: "{{ state }}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
      register: vpcoutput

    # - debug:
    #     var: vpcoutput 

    - name: Create Public Subnet 1
      ec2_vpc_subnet:
        vpc_id: "{{ vpcoutput.vpc.id }}"
        cidr: "{{ PubSub1Cidr }}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        map_public: yes
        state: "{{ state }}"
        resource_tags:
          Name: mikail-pub_subnet_1
      register: pub_subnet_1

    - name: Create Public Subnet 2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcoutput.vpc.id }}"
        cidr: "{{ PubSub2Cidr }}"
        region: "{{ region }}"
        az: "{{ zone2 }}"
        map_public: yes
        state: "{{ state }}"
        resource_tags:
          Name: mikail-pub_subnet_2
      register: pub_subnet_2

    - name: Create Public Subnet 3
      ec2_vpc_subnet:
        vpc_id: "{{ vpcoutput.vpc.id }}"
        cidr: "{{ PubSub3Cidr }}"
        region: "{{ region }}"
        az: "{{ zone3 }}"
        map_public: yes
        state: "{{ state }}"
        resource_tags:
          Name: mikail-pub_subnet_3
      register: pub_subnet_3

    - name: Create Private Subnet 1
      ec2_vpc_subnet:
        vpc_id: "{{ vpcoutput.vpc.id }}"
        cidr: "{{ PrivSub1Cidr }}"
        region: "{{ region }}"
        az: "{{ zone1 }}"
        map_public: yes
        state: "{{ state }}"
        resource_tags:
          Name: mikail-priv_subnet_1
      register: priv_subnet_1

    - name: Create Private Subnet 2
      ec2_vpc_subnet:
        vpc_id: "{{ vpcoutput.vpc.id }}"
        cidr: "{{ PrivSub2Cidr }}"
        region: "{{ region }}"
        az: "{{ zone2 }}"
        map_public: yes
        state: "{{ state }}"
        resource_tags:
          Name: mikail-priv_subnet_2
      register: priv_subnet_2

    - name: Create Private Subnet 3
      ec2_vpc_subnet:
        vpc_id: "{{ vpcoutput.vpc.id }}"
        cidr: "{{ PrivSub3Cidr }}"
        region: "{{ region }}"
        az: "{{ zone3 }}"
        map_public: yes
        state: "{{ state }}"
        resource_tags:
          Name: mikail-priv_subnet_3
      register: priv_subnet_3

    - name: Create Internet Gateway
      ansible.builtin.ec2_vpc_igw:
        vpc_id: "{{ vpcoutput.vpc.id }}"
        region: "{{ region }}"
        state: "{{ state }}"
        resource_tags:
          Name: mikail_IGW
      register: igw_output

    - name: Create Public Route Table
      ansible.builtin.ec2_vpc_route_table:
        vpc_id: "{{ vpcoutput.vpc.id }}"
        region: "{{ region }}"
        state: "{{ state }}"
        tags:
          Name: mikail_PubRT
        subnets:
          - "{{ pub_subnet_1.subnet.id }}"
          - "{{ pub_subnet_2.subnet.id }}"
          - "{{ pub_subnet_3.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw_output.gateway_id }}"
      register: public_route_table_output

    - name: Create NAT gateway
      ec2_vpc_nat_gateway:
        subnet_id: "{{ pub_subnet_1.subnet.id }}"
        state: "{{ state }}"
        region: "{{ region }}"
        wait: yes
        if_exist_do_not_create: true
      register: nat_gateway_output

    - name: Create route table for NAT gateway
      ec2_vpc_route_table:
        vpc_id: "{{ vpcoutput.vpc.id }}"
        state: "{{ state }}"
        region: "{{ region }}"
        tags:
          Name: route_table_for_NAT
        subnets:
          - "{{ priv_subnet_1.subnet.id }}"
          - "{{ priv_subnet_2.subnet.id }}"
          - "{{ priv_subnet_3.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            nat_gateway_id: "{{ nat_gateway_output.nat_gateway_id }}"
      register: route_table_output_NAT

    - debug:
        var: "{{ item }}"
      loop:
        - vpcoutput
        - pub_subnet_1.subnet.id
        - pub_subnet_2.subnet.id
        - pub_subnet_3.subnet.id
        - priv_subnet_1.subnet.id
        - priv_subnet_2.subnet.id
        - priv_subnet_3.subnet.id
        - igw_output.gateway_id
        - public_route_table_output.route_table.id
        - nat_gateway_output.nat_gateway_id
        - route_table_output_NAT.route_table.id

    - set_fact:
        vpcid: "{{ vpcoutput.vpc.id }}"
        pub_subnet_1_id: "{{ pub_subnet_1.subnet.id }}"
        pub_subnet_2_id: "{{ pub_subnet_2.subnet.id }}"
        pub_subnet_3_id: "{{ pub_subnet_3.subnet.id }}"
        priv_subnet_1_id: "{{ priv_subnet_1.subnet.id }}"
        priv_subnet_2_id: "{{ priv_subnet_2.subnet.id }}"
        priv_subnet_3_id: "{{ priv_subnet_3.subnet.id }}"
        igw_id: "{{ igw_output.gateway_id }}"
        public_route_table_id: "{{ public_route_table_output.route_table.id }}"
        nat_gateway_id: "{{ nat_gateway_output.nat_gateway_id }}"
        route_table_NAT_id: "{{ route_table_output_NAT.route_table.id }}"
        cacheable: yes
        
    - name: Copy variables into a file
      ansible.builtin.copy:
        content: "region: {{ region }}\nvpcid: {{ vpcoutput.vpc.id }}\npub_subnet_1_id: {{ pub_subnet_1.subnet.id }}\npub_subnet_2_id: {{ pub_subnet_2.subnet.id }}\npub_subnet_3_id: {{ pub_subnet_3.subnet.id }}\npriv_subnet_1_id: {{ priv_subnet_1.subnet.id }}\npriv_subnet_2_id: {{ priv_subnet_2.subnet.id }}\npriv_subnet_3_id: {{ priv_subnet_3.subnet.id }}\nigw_id: {{ igw_output.gateway_id }}\npublic_route_table_id: {{ public_route_table_output.route_table.id }}\nnat_gateway_id: {{ nat_gateway_output.nat_gateway_id }}\nroute_table_NAT_id: {{ route_table_output_NAT.route_table.id }}"   
        dest: /home/ubuntu/output_vars
   