- name: windows server configuration
  hosts: windows_servers
  tasks:
    - name: Set timezone to 'Romance Standard Time' (GMT+01:00)
      community.windows.win_timezone:
        timezone: Romance Standard Time

    - name: Change the hostname to sample-hostname
      ansible.windows.win_hostname:
        name: mikail-hostname
      register: res

    - name: see the result
      debug:
        var: res  

    - name: Reboot
      ansible.windows.win_reboot:
      when: res.reboot_required
 