- name: create a user using a variable
  hosts: all
  become: true
  vars:
    user: lisa
    ansible_ssh_private_key_file: "/home/ec2-user/My_Key.pem"
  vars_files:
    - secret-2.yaml  
  tasks:
    - name: create a user {{ user }}
      user:
        name: "{{ user }}"
        password: "{{ password | password_hash ('sha512') }}"
    - debug:
        msg: "private ip is {{ foo }}"

    - debug:
        msg: "instance id is {{ boo }}"

    - debug:
        msg: "my key file is {{ key }}"

    - debug: 
        msg: "host is  {{ ansible_host }}"    